name       : perl-extutils-depends
version    : '0.8000'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/ExtUtils-Depends-0.8000.tar.gz : 780ff72128c04c2a22e6801187aa9c58cab298407f6e9d062706af1c250bbe98
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::Depends - Easily build XS extensions that depend on XS extensions
description: |
    This module tries to make it easy to build Perl extensions that use functions and typemaps provided by other perl extensions. This means that a perl extension is treated like a shared library that provides also a C and an XS interface besides the perl one.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
