name       : perl-extutils-depends
version    : 0.405
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/X/XA/XAOC/ExtUtils-Depends-0.405.tar.gz : 8ad6401ad7559b03ceda1fe4b191c95f417bdec7c542a984761a4656715a8a2c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::Depends - Easily build XS extensions that depend on XS extensions
description: |
    This module tries to make it easy to build Perl extensions that use functions and typemaps provided by other perl extensions. This means that a perl extension is treated like a shared library that provides also a C and an XS interface besides the perl one.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
