name       : perl-extutils-depends
version    : '0.8001'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/ExtUtils-Depends-0.8001.tar.gz : 673c4387e7896c1a216099c1fbb3faaa7763d7f5f95a1a56a60a2a2906c131c5
homepage   : https://metacpan.org/pod/ExtUtils::Depends
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::Depends - Easily build XS extensions that depend on XS extensions
description: |
    This module tries to make it easy to build Perl extensions that use functions and typemaps provided by other perl extensions. This means that a perl extension is treated like a shared library that provides also a C and an XS interface besides the perl one.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
